apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-hello-world.fullname" . }}
  labels:
    {{- include "nginx-hello-world.labels" . | nindent 4 }}
data:
  index.html: |-
    {{- .Files.Get "files/index.html" | nindent 4 }}
